/// THIS CLASS IS USED TO MANAGE ALL ASSETS USED IN THE APPLICATION...
class AssetUtilities {
  /// [APPLICATION LOGO]...
  static const String applicationlogo = "assets/logo.png";

  /// SVG ICONS...
  static const String checkTrueStrokeSvg = "assets/svg/check.svg";
}
